name: Update Homebrew Formula

on:
  schedule:
    # Runs at 00:00 on the 1st day of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up jq
        run: sudo apt-get install jq
      - name: Run update script
        run: ./update.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update has.rb to latest version"
          title: "Update has.rb Homebrew formula to latest version"
          body: |
            This PR updates the has.rb Homebrew formula to the latest version.

            Changes made:
            - Updated download URL to latest release
            - Updated SHA256 checksum

            This is an automated update performed by GitHub Actions.
          branch: update-has-formula
          delete-branch: true
